### ISSUE TITLE
Scandit inverted code

### ISSUE THREAD

**Issue by mppub** [PharmaLedger-IMI/epi-workspace#192]
# Result
Investigate inverted code behavior and possibly fix it

**Comment by mppub** [comment]
Testing notes: I have tested the inverted code scan with image from #101 as the inverted codes I created with the apps I tried were not recognized. The image is: 
![image](https://user-images.githubusercontent.com/71266598/117950269-4d720280-b313-11eb-84db-0f526bca139e.png)

If you notice, the date format is in incorrect format (22 - 12 - 00) meaning 2022 - December - `undefined` but his is an issue of the code not of the scanner as you probably wont count days starting from 0 and months and years starting from 1.

**Comment by rite2bala** [comment]
Hi @mppub 
Asper the current requirements, the expiry date can be without a day as well. 
meaning - 2022 December is also a valid date - (even without a day)

If this is a part of Scandit - it needs to be fixed

If it is a part of the current PWA application , this was identified and fixed by Cosmin.
