### ISSUE TITLE
Interrupted build process is crushing

### ISSUE THREAD

**Issue by salboaie** [PharmaLedger-IMI/epi-workspace#263]
Logger not available, using console
Redefining require for node
Dossier updating...
Deleting /
Build process of <pdm-theme> failed.
Error: Could not delete path '/'(Invalid path </>)
at ErrorWrapper (/home/tvenceslau/workspace/pharmaledger/traceability/fgt-workspace/privatesky/psknode/bundles/openDSU.js:19657:22)
at createOpenDSUErrorWrapper (/home/tvenceslau/workspace/pharmaledger/traceability/fgt-workspace/privatesky/psknode/bundles/openDSU.js:19687:12)
at _err (/home/tvenceslau/workspace/pharmaledger/traceability/fgt-workspace/privatesky/psknode/bundles/openDSU.js:19436:42)
at /home/tvenceslau/workspace/pharmaledger/traceability/fgt-workspace/privatesky/psknode/bundles/openDSU.js:18798:15
at /home/tvenceslau/workspace/pharmaledger/traceability/fgt-workspace/privatesky/psknode/bundles/openDSU.js:3435:57
at /home/tvenceslau/workspace/pharmaledger/traceability/fgt-workspace/privatesky/psknode/bundles/openDSU.js:3158:17
at /home/tvenceslau/workspace/pharmaledger/traceability/fgt-wor

**Comment by vladbalmos** [comment]
The issue stems from the fact that the build process is not atomic. Any buildDossier process comprised of a delete root (/) operation followed by an "add folder" operation can fail if the "add" op is interrupted before it commits its changes to the BrickMap.

If the crash occurs after the delete operation succeeds, any subsequent builds will fail because the root path has already been deleted by the previous process.

The delete op throws an exception if a leaf in the BrickMap tree doesn't exists, or if that leaf has been marked as deleted - when the first delete happens the "deleted" flag is added to the root node of the BrickMap tree, thus causing subsequent deletes to fail.

IMHO I consider this to be normal behaviour and it is inline with the way a generic file system delete operation works: `rm non-existent-file` fails on Linux. Daniel Sava introduced a fix (https://github.com/PrivateSky/bar/commit/ea0a35d1c29daf61e0274e93cc470d8d5334e01e) that forces the delete op to succeed even if the file or directory doesn't exists (the equivalent of a `rm -f non-existent-file`) - this will resolve the issue

Another alternative fix would be to make the build process atomic (use batch anchoring).

Changing the BrickMap structure by removing the "deleted" attribute is unadvisable since the diffing/merging BrickMap's strategies depend on it.

I will go ahead and update the error messages to better reflect the state of the operations.

Please let me know if you'd like me to follow more on this. 
Thanks

**Comment by salboaie** [comment]
Please do the batch anchoring in the dt as it will anyway reduce the number of useless anchors

**Comment by vladbalmos** [comment]
Batch anchoring added in commit (https://github.com/PrivateSky/OpenDSU/commit/831645d50f548d820e3152f0bc06bd68eff13428)
