### ISSUE TITLE
Create error JSON Message responses on message mapping

### ISSUE THREAD

**Issue by salboaie** [PharmaLedger-IMI/epi-workspace#314]
-  send the JSON to an ReceiverID endpoint (pair between senderId and endpoints configurable in messageMapping middleware)
- create a demo purpose endpoint (as APIHub midleware)
- provide a link from the DSU fabric (open in new tab to show it)
- create a list of all possible errors code

Details on how the response message should look like: 
![image](https://user-images.githubusercontent.com/78138966/129065978-5f4fadc5-0419-4948-9855-cb164b571f88.png)

and examples attached for the product master. One example to show successfully processed message and one example showing how an error could look like. 
[ePI_Product_response_examples.zip](https://github.com/PharmaLedger-IMI/epi-workspace/files/6969937/ePI_Product_response_examples.zip)

For the batch its the same.

**Comment by adiganga2002** [comment]
Tabel with identified error messages : 

[ErrorCodes.xlsx](https://github.com/PharmaLedger-IMI/epi-workspace/files/6981584/ErrorCodes.xlsx)

**Comment by steinso2** [comment]
@adiganga2002 
I have questions on the error codes: 
"Invalid message format"   ------>>>> ok
"Database operation failed"   ------>>>> what is wrong that this can happen?
"Message is not an Object"    ------>>>> what is wrong that this can happen?
"Mapping Engine is digesting messages for the moment"    ------>>>> does this mean we need to send the files again or just wait until they are processed? 
"Not able to digest message due to missing mapping"     ------>>>> what is wrong that this can happen?
"Caught error during mapping"     ------>>>> here we need to be more precise what field is wrong. 
"Fail to create a batch for a missing product"   ------>>>> ok

Additionally on the batch error codes, where can I see them in the UI? Maybe we can discuss it in a call?

**Comment by adiganga2002** [comment]
@steinso2 
"Database operation failed" - is thrown when a database operation fails. E.g. Mapping engine finds a product DSU that exists into the Blockchain network but not into the Company shared database. 
"Message is not an Object" - is thrown when we receive a message and mapping engine fails to JSON decode it.
"Mapping Engine is digesting messages for the moment" - is equivalent to a standard Internal Server Error and it means that a a code routine forced the mapping engine to digest a new message group. After the finalization of task #207 the messages will not be lost and there is no need to send them again
"Not able to digest message due to missing mapping" - is thown when the mapping engine receives a message type for which can't find a mapping e.g. an external message provider is pushing a message that it is correct: JSON format, a type header different then product, batch, leaflet or productphoto 

I'm available for a call when you are available.
