### ISSUE TITLE
User app: Processing the scanned data does not display name of the drug & does not verify serial number

### ISSUE THREAD

**Issue by mppub** [PharmaLedger-IMI/epi-workspace#318]
Comes from issue, after the successful Scandit scan the screen that follows fails to show:
- drug name
- serial number check

this issue comes from: #286

**Comment by rite2bala** [comment]
Can you pls also specify who will be solving this issue?

**Comment by mppub** [comment]
Hi @rite2bala I have tested this locally and I got a valid result containing the serial number check and drug name, I guess this is because there is not deployed new version yet(the same as I was mentioning before): 
![image](https://user-images.githubusercontent.com/71266598/128518473-ceb5e473-1225-4ce7-aeee-63dc02cbef00.png)

**Comment by rite2bala** [comment]
Hi @mppub 
In order to resolve the confusion - 
1. The last deployment was done in QA on 19 July 2021 and same version in UAT on 23 July 2021.
 Could you pls confirm if code commits from your end were done after 19th July?
 
2. Which code repository or specific branch  are you using while testing - is the code committed to the main branch? 

3. If you are testing the iOS app - the last version of the iOS app available with us for testing is Thursday, 8 July 2021.
Was there a change to the code after 8 July 2021?

We really want this issue to be solved to be able to test multiple other things including scanning an entire PDF of codes using Scandit 
[App.and.DSU.Fabric.Feedback.v0.2.pdf](https://github.com/PharmaLedger-IMI/epi-workspace/files/6949343/App.and.DSU.Fabric.Feedback.v0.2.pdf)

This can turn business critical and can lead to escalation by the end of Aug 12th with the Singapore demo just around the corner.

**Comment by mppub** [comment]
Hi @rite2bala 
1. The deployment is done on Novartis side, lets ask someone from those people doing the releases
2. It is the master branch always the latest version (but I had the same result one month ago)
3. I am testing PWA / WEb version
