### ISSUE TITLE
The messages should not be able to control product and batch version. Change version wording to  "Change number" in UI

### ISSUE THREAD

**Issue by salboaie** [PharmaLedger-IMI/epi-workspace#332]

**Comment by steinso2** [comment]
@salboaie: I changed the issue description because 

- the product and the batch (change) version is a version number, starting from 1 and increasing by 1, that should increase by each change to a product or a batch AND should not be controlled by an externally transmitted field
- the field "leaflet version" (new filed name to not to mix up with the product or batch version, most probably will be "**artwork identifier**") is an external number given by the leaflet source system to identify the leaflet and is also printed on the paper leaflet. 
- this field **artwork identifier** need to be included in the batch and product json, and needs to be shown close to the uploaded leaflet (on product and batch level) in the DSU.

**_Background info:_** 
**artwork identifier**: This is printed on the leaflet, and [number based on the packaging site local material number for the printed component]+[approving regulatory function]. This number is reflected in OneArt as well.
e.g. 
1234567 DE = local material 1234567 that is approved by regulatory in Germany
2345678 R25 = local material 2345678 that is approved by both Germany and Austria (shared leaflet)

Any questions, please let me know.

**Comment by adiganga2002** [comment]
@steinso2 Is this artwork identifier a mandatory field?

**Comment by steinso2** [comment]
Hi @adiganga2002 Good question! No, it is not a mandatory field. In the future most likely but we don't have it yet for all.
