### ISSUE TITLE
OBA - Resend failed transactions to blockchain

### ISSUE THREAD

**Issue by skutner** [PharmaLedger-IMI/epi-workspace#919]

**Comment by macdoda03** [comment]
Dear Sinica,
As promised during our call last Friday I have had a discussion with James regarding the “optimistic approach to anchoring” and audit trail entry requirements:
•	We are required to have an audit trail when the EW user creates the initial request
•	We are required to have an audit trail entry when the actual request is anchored
•	We are required to have a notification to the end user indicating completion 
In addition, as discussed we will need to have be logging and monitoring in order to be able to react in a “timely” manner to delays in anchoring
