### ISSUE TITLE
Investigate how you can revert a permission access deny (Web/iOS/Android)

### ISSUE THREAD

**Issue by salboaie** [PharmaLedger-IMI/epi-workspace#926]

**Comment by daniel-visoiu** [comment]
**Android**

**Permission dialog visibility**
Starting in **Android 11**, if the user taps **Deny** for a specific permission more than once during your app's lifetime of installation on a device, **the user doesn't see the system permissions dialog if your app requests that permission again**. The user's action implies "don't ask again." On previous versions, users would see the system permissions dialog each time your app requested a permission, unless the user had previously selected a "don't ask again" checkbox or option. This behavior change in Android 11 discourages repeated requests for permissions that users have chosen to deny. Taken from [Permissions updates in Android 11](https://developer.android.com/about/versions/11/privacy/permissions#dialog-visibility).

The Permission API has a callback which notify if the user has given or denied permission when the permission is requested. After the first two times the permission is rejected with **Never**, the Permission API callback will be called notifying that the permission is denied, but the Permission Dialog is not displayed.

[Android allows](https://developer.android.com/training/permissions/requesting.html) a way to know programmatically, if a permission was previously rejected by the user. To help find the situations where you need to provide extra explanation, the system provides the **Activity.shouldShowRequestPermissionRationale(String)** method. This method returns true if the app has requested this permission previously and the user denied the request. That indicates that you should probably explain to the user why you need the permission.

If the user turned down the permission request in the past and chose the Don't ask again option in the permission request system dialog, this method returns false. The method also returns false if the device policy prohibits the app from having that permission.

**Android recommends** that if a permission is denied and **Activity.shouldShowRequestPermissionRationale(String)** returns true,  then an educational UI should be shown that explains to the user why the app requires this permission for a specific feature to behave as expected. In this UI, a "cancel" or "no thanks" button should be included that allows the user to continue using the app without granting the permission.

The following sample could be shown when Android detects that an detailed explanation must be provided to the user.
![image](https://user-images.githubusercontent.com/9691701/191836115-6707e248-c4fc-4eb7-8fb2-c78bfc204618.png)

The only impediment is that the **Activity.shouldShowRequestPermissionRationale(String)** returns true even after the second time the user denied the permission (and so on). Because of this, the **Permission Dialog** won't be shown by Android. So there is no direct way of detecting if the Permission Dialog can be shown or not. Because if the Permission Dialog won't be shown by Android, then the provided message to the user should instruct him to allow the permission by himself in the **Android Settings** for the Application.
